# Hardik Ajay Patil Assignment 1


In [1]:
import numpy as np

## Make a python list => [1,2,3,4,5] Convert it into numpy array and print it

In [3]:
lst=[1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [4]:
lst1=np.array(lst)
lst1

array([1, 2, 3, 4, 5])

## Make a python matrix (3 x 3) => [[1,2,3],[4,5,6],[7,8,9]] Convert it into numpy array and print it

In [5]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

## [ [1,3,5],

## [7,9,11],

## [13,15,17] ]

In [16]:
matrix1=np.arange(1,18,2).reshape(3,3)
np.array(matrix1)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

## Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [34]:
a=np.random.randint(10,size=10)
a

array([0, 8, 2, 8, 0, 7, 5, 7, 5, 4])

## Create numpy array => [1,2,3,4,5] and convert it to 2D array with 5 rows

In [37]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [40]:
arr2=arr.reshape(5,1)
arr2

array([[1],
       [2],
       [3],
       [4],
       [5]])

## Print the shape of the above created array

In [42]:
arr2.shape

(5, 1)

## Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [43]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10])
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr3[2],arr3[3],arr3[8]

(3, 4, 9)

## Print alternate elements of that array

In [47]:
arr3[0::2]

array([1, 3, 5, 7, 9])

## Change last 3 elements into 100 using broadcasting and print

In [48]:
arr3[7:]=100
arr3

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

## Create a 5 x 5 matrix (fill it with any element you like), print it.

## Then print the middle (3 x 3) matrix.

In [57]:
arr=np.array([[1., 2, 3, 4, 5],
       [6, 7, 8, 9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 18, 19],
       [21, 22, 23, 24, 25]])

In [59]:
arr[1:4, 1:4]

array([[ 7.,  8.,  9.],
       [12., 13., 14.],
       [17., 18., 18.]])